	virtual void BookHistos();
	virtual void JetSet(string JetSetType);
	virtual void ParticleSelection();
	virtual bool RegionSelector_bjetVeto();
	virtual bool RegionSelector_bjetSelect();
	virtual void GenerateVariables();
	virtual void FillAllData_PreCut();
	virtual void DrawHistos();
	virtual void CutAndFill();
	virtual void CutAndFill_bjet();
